version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
  pre_build:
    commands:
      - yarn install --frozen-lockfile
  build:
    commands:
      - echo Build started on `date`
      - yarn run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading to S3 Bucket
      - aws s3 sync --delete --cache-control max-age=0,no-cache,no-store,must-revalidate build/ "s3://${DEPLOYMENT_BUCKET}/me"
      - echo Upload completed on `date`
      - echo Creating cache invalidation
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
      - echo Invalidation completed on `date`
