steps:
  - name: node
    entrypoint: npm
    args: [ "install" ]
  - name: node
    entrypoint: npm
    args: [ "run", "build" ]
artifacts:
  objects:
    location: "gs://surc.dev"
    paths: [ "dist/" ]
