steps:
  - name: node
    timeout: 500s
    entrypoint: npm
    args: [ "install" ]
  - name: node
    timeout: 500s
    entrypoint: npm
    args: [ "run", "build" ]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:alpine"
    timeout: 10s
    entrypoint: gsutil
    args: [ "-m", "rm", "gs://surc.dev/**"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:alpine"
    timeout: 10s
    entrypoint: gsutil
    args: [ "-m", "cp", "-r", "dist/**", "gs://surc.dev/"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:alpine"
    timeout: 10s
    entrypoint: gsutil
    args: [ "-h", "Cache-Control:no-cache,max-age=0", "-m", "cp", "-r", "dist/index.html", "gs://surc.dev/"]
